services:
  - type: web
    name: flixster
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html 